import pandas as pd
import matplotlib.pyplot as plt
import os

def generation_coal(x, y):
    '''
    Ploting the graph to compare the electricity generation from coal of three different countries.
    Input: x is the processed data that includes the generation from 2007 to 2017;
           y is the data that includes the electricity generation from of different countries.
    Output: Graph with three curves representing the generation of China, India and the US.
    
    by Cong Zhao
    '''
    assert isinstance(x, pd.DataFrame)
    assert isinstance(y, pd.DataFrame) 
    # Ensure the three countries in the dataset
    assert 'China' in y['Country Name'].tolist()
    assert 'United States' in y['Country Name'].tolist()
    assert 'India' in y['Country Name'].tolist()
    
    China=y.loc[y['Country Name']=='China']
    US = y.loc[y['Country Name']=='United States']
    India = y.loc[y['Country Name']=='India']
    China_new=China.loc[:,'2005':'2015']#.tolist()
    US_new=US.loc[:,'2005':'2015']#.tolist()
    India_new=India.loc[:,'2005':'2015']#.tolist()
    China_new = China_new.iloc[0].tolist()
    US_new = US_new.iloc[0].tolist()
    India_new = India_new.iloc[0].tolist()
    yr_range = range(2005,2016)
    China_new
    plt.figure(figsize=(9,6))
    plt.plot( yr_range, China_new, marker='o', markerfacecolor='blue', markersize=10, color='skyblue', linewidth=3,label='China')
    plt.plot( yr_range, US_new, marker='o', markerfacecolor='green', markersize=10, color='olive', linewidth=3,label='US')
    plt.plot( yr_range, India_new, marker='o', markerfacecolor='red', markersize=10, color='pink', linewidth=3,label='India')
    plt.legend()
    plt.title('% of electricity generated by coal')
    plt.xlabel('year')
    plt.ylabel('%of total generation')
    plt.grid()

x = pd.read_excel(os.path.join('dataset,'annual_generation_state.xls'))
x = x.loc[x['YEAR']>2006]
y = pd.read_csv(os.path.join('dataset','percent_coal.csv'))
generation_coal(x, y)